# Generates PR_DESCRIPTION.generated.md from commits ahead of origin/main (or master/develop).
# Run from repo root: .\scripts\generate-pr-description.ps1
# Env: $env:PR_DESCRIPTION_OUT, $env:GIT_PR_REMOTE

$ErrorActionPreference = "Continue"

$repoRoot = git rev-parse --show-toplevel 2>$null
if (-not $repoRoot -or $LASTEXITCODE -ne 0) { exit 0 }
Set-Location $repoRoot

$out = if ($env:PR_DESCRIPTION_OUT) { $env:PR_DESCRIPTION_OUT } else { "PR_DESCRIPTION.generated.md" }
$remote = if ($env:GIT_PR_REMOTE) { $env:GIT_PR_REMOTE } else { "origin" }

git remote get-url $remote 2>$null | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "generate-pr-description: no remote '$remote' — skip"
    exit 0
}

$upstream = $null
foreach ($base in @("main", "master", "develop")) {
    $ref = "${remote}/${base}"
    git rev-parse --verify $ref 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) {
        $upstream = $ref
        break
    }
}

if (-not $upstream) {
    Write-Host "generate-pr-description: no ${remote}/main|master|develop — skip (fetch remotes?)"
    exit 0
}

$branch = (git rev-parse --abbrev-ref HEAD).Trim()
$range = "${upstream}..HEAD"
$titleHint = git log -1 --pretty=%s HEAD 2>$null
if ($titleHint -and $titleHint.Length -gt 160) {
    $titleHint = $titleHint.Substring(0, 160)
}
if (-not $titleHint) { $titleHint = "commit message" }

$upstreamShort = git rev-parse --short $upstream 2>$null
if (-not $upstreamShort) { $upstreamShort = "?" }

$commitLines = @(git log $range --pretty='format:- %s (`%h`)' 2>$null)
$commitsText = if ($commitLines.Count -gt 0) { ($commitLines -join "`n") } else { "_unable to list commits_" }

$statText = git diff --stat $range 2>$null
if (-not $statText) { $statText = "(no diff)" }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("## Title (edit)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("<!-- Suggestion: $titleHint -->")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Summary")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("- Branch: ``$branch``")
[void]$sb.AppendLine("- Compare: ``$range`` (base ``$upstream`` @ ``$upstreamShort``)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("### Commits")
[void]$sb.AppendLine("")
[void]$sb.AppendLine($commitsText)
[void]$sb.AppendLine("")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("### Files changed")
[void]$sb.AppendLine("")
[void]$sb.AppendLine('```')
[void]$sb.AppendLine($statText)
[void]$sb.AppendLine('```')
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Testing")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("- [ ] ``gradlew test`` (or ``.\gradlew.bat test``)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Notes")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("_Generated by ``scripts/generate-pr-description.ps1``. Copy into GitHub/GitLab PR body and edit._")

[System.IO.File]::WriteAllText((Join-Path (Get-Location) $out), $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

Write-Host "generate-pr-description: wrote $out"
