#!/usr/bin/env sh
# Generates PR_DESCRIPTION.generated.md from commits ahead of origin/main (or master/develop).
# Run manually: ./scripts/generate-pr-description.sh
# Env: PR_DESCRIPTION_OUT=path  GIT_PR_REMOTE=origin

set -eu

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
cd "$REPO_ROOT"

OUT="${PR_DESCRIPTION_OUT:-PR_DESCRIPTION.generated.md}"
REMOTE="${GIT_PR_REMOTE:-origin}"

if ! git remote get-url "$REMOTE" >/dev/null 2>&1; then
  echo "generate-pr-description: no remote '$REMOTE' — skip" >&2
  exit 0
fi

pick_upstream_ref() {
  for base in main master develop; do
    if git rev-parse --verify "${REMOTE}/${base}" >/dev/null 2>&1; then
      echo "${REMOTE}/${base}"
      return 0
    fi
  done
  return 1
}

if ! UPSTREAM=$(pick_upstream_ref); then
  echo "generate-pr-description: no ${REMOTE}/main|master|develop — skip (fetch remotes?)" >&2
  exit 0
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
RANGE="${UPSTREAM}..HEAD"
TITLE_HINT=$(git log -1 --pretty=%s HEAD 2>/dev/null | head -c 160 || true)
UPSTREAM_SHORT=$(git rev-parse --short "$UPSTREAM" 2>/dev/null || echo "?")

{
  printf '%s\n\n' "## Title (edit)"
  printf '<!-- Suggestion: %s -->\n\n' "${TITLE_HINT:-commit message}"
  printf '%s\n\n' "## Summary"
  printf '%s\n' "- Branch: \`${BRANCH}\`"
  printf '%s\n' "- Compare: \`${RANGE}\` (base \`${UPSTREAM}\` @ \`${UPSTREAM_SHORT}\`)"
  printf '\n%s\n\n' "### Commits"
  if git rev-parse "$UPSTREAM" >/dev/null 2>&1; then
    git log "$RANGE" --pretty='format:- %s (`%h`)' 2>/dev/null || printf '%s\n' "_unable to list commits_"
  else
    printf '%s\n' "_invalid upstream_"
  fi
  printf '\n%s\n\n' "### Files changed"
  printf '%s\n' '```'
  git diff --stat "$RANGE" 2>/dev/null || printf '%s\n' "(no diff)"
  printf '%s\n\n' '```'
  printf '%s\n\n' "## Testing"
  printf '%s\n' "- [ ] \`gradlew test\` (or \`./gradlew test\`)"
  printf '\n%s\n\n' "## Notes"
  printf '%s\n' "_Generated by \`scripts/generate-pr-description.sh\`. Copy into GitHub/GitLab PR body and edit._"
} >"$OUT"

echo "generate-pr-description: wrote $OUT" >&2
exit 0
